In [95]:
import torch
import numpy as np

np.set_printoptions(precision=3)

a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.tensor(b)

print(t_a)
print(t_b)


tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


Transpose: 

In [96]:
t = torch.rand(3, 5, 3, 2)
t_tr = torch.transpose(t, 0, 1)

print(t.shape, ' --> ', t_tr.shape)
print(t, ' --> ', t_tr)

torch.Size([3, 5, 3, 2])  -->  torch.Size([5, 3, 3, 2])
tensor([[[[0.6397, 0.9743],
          [0.8300, 0.0444],
          [0.0246, 0.2588]],

         [[0.9391, 0.4167],
          [0.7140, 0.2676],
          [0.9906, 0.2885]],

         [[0.8750, 0.5059],
          [0.2366, 0.7570],
          [0.2346, 0.6471]],

         [[0.3556, 0.4452],
          [0.0193, 0.2616],
          [0.7713, 0.3785]],

         [[0.9980, 0.9008],
          [0.4766, 0.1663],
          [0.8045, 0.6552]]],


        [[[0.1768, 0.8248],
          [0.8036, 0.9434],
          [0.2197, 0.4177]],

         [[0.4903, 0.5730],
          [0.1205, 0.1452],
          [0.7720, 0.3828]],

         [[0.7442, 0.5285],
          [0.6642, 0.6099],
          [0.6818, 0.7479]],

         [[0.0369, 0.7517],
          [0.1484, 0.1227],
          [0.5304, 0.4148]],

         [[0.7937, 0.2104],
          [0.0555, 0.8639],
          [0.4259, 0.7812]]],


        [[[0.6607, 0.1251],
          [0.6004, 0.6201],
          [0.1652, 0.262

Reshape

In [97]:
t = torch.rand(30)
t_r = t.reshape(5, 6)
print(t)
print(t_r)

tensor([0.1976, 0.5628, 0.9983, 0.1842, 0.7664, 0.2233, 0.0299, 0.3937, 0.7881,
        0.9642, 0.1895, 0.6085, 0.9314, 0.8313, 0.8116, 0.8553, 0.8163, 0.6291,
        0.1581, 0.0801, 0.2709, 0.4418, 0.1935, 0.6829, 0.6547, 0.3868, 0.6922,
        0.6616, 0.8053, 0.8367])
tensor([[0.1976, 0.5628, 0.9983, 0.1842, 0.7664, 0.2233],
        [0.0299, 0.3937, 0.7881, 0.9642, 0.1895, 0.6085],
        [0.9314, 0.8313, 0.8116, 0.8553, 0.8163, 0.6291],
        [0.1581, 0.0801, 0.2709, 0.4418, 0.1935, 0.6829],
        [0.6547, 0.3868, 0.6922, 0.6616, 0.8053, 0.8367]])


Squeze - remove unnecessary dimensions (dimensions that have size 1, which are not needed)

In [98]:
t = torch.zeros(1, 2, 1, 4, 1)
print(t)
print(t.shape)
t_s = torch.squeeze(t, 2)
print(t_s)
print(t_s.shape)

tensor([[[[[0.],
           [0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.],
           [0.]]]]])
torch.Size([1, 2, 1, 4, 1])
tensor([[[[0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.]]]])
torch.Size([1, 2, 4, 1])


Multiply element-wise (uniform and standard random distribution samples)

In [99]:
torch.manual_seed(1)
t1 = torch.rand(5, 2)  # uniform distribution
print(t1)

t1 = 2 * t1 - 1
t2 = torch.normal(mean=0, std=1, size=(5, 2))  # standard normal distribution

t3 = torch.multiply(t1, t2)  # element-wise multiplication
print(t3)
print(t3.shape)

t4 = torch.mean(t3, axis=0)  # mean over elements of first axis (column 0 and 1)
print(t4)

t5 = torch.sum(t3, axis=0) / 5  # by hand computation of mean
print(t5)

tensor([[0.7576, 0.2793],
        [0.4031, 0.7347],
        [0.0293, 0.7999],
        [0.3971, 0.7544],
        [0.5695, 0.4388]])
tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])
torch.Size([5, 2])
tensor([ 0.3491, -0.0436])
tensor([ 0.3491, -0.0436])


Matrix multiplication

In [100]:
t6 = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(t6)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [101]:
t7 = torch.matmul(torch.transpose(t1, 0, 1), t2)
print(t7)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])
